FROM resin/raspberrypi3-debian:stretch as builder

# Let's create the builder

RUN apt-get update \
 && apt-get install -y \
    autoconf \
    automake \
    build-essential \
    git \
    libtool \
    libgmp-dev \
    libsqlite3-dev \
    python \
    python3 \
    net-tools \
    zlib1g-dev

ARG CORE_VERSION="0.16.3"
ENV TARBALL bitcoin-${CORE_VERSION}-arm-linux-gnueabihf.tar.gz
ENV URL https://bitcoincore.org/bin/bitcoin-core-${CORE_VERSION}

RUN wget ${URL}/SHA256SUMS.asc \
 && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys "01EA5486DE18A882D4C2684590C8019E36C2E964" \
 && gpg --verify SHA256SUMS.asc \
 && wget ${URL}/${TARBALL} \
 && grep ${TARBALL} SHA256SUMS.asc | sha256sum -c - \
 && tar -xzC . -f ${TARBALL} bitcoin-${CORE_VERSION}/bin/bitcoin-cli --strip-components=2 \
 && rm -rf ${TARBALL} SHA256SUMS.asc

ARG DEVELOPER=1
RUN git clone https://github.com/ElementsProject/lightning.git \
 && cd lightning && ./configure && make -j3 DEVELOPER=${DEVELOPER}

# Let's create the actual image that will be run

FROM resin/raspberrypi3-debian:stretch

RUN apt-get update \
 && apt-get install -y \
    libgmp-dev \
    libsqlite3-dev \
    net-tools \
    zlib1g-dev \
    libtool \
    gosu \
 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

VOLUME ["/.bitcoin", "/.lightning"]

COPY --from=builder /lightning/cli/lightning-cli /usr/bin
COPY --from=builder /lightning/lightningd/lightning* /usr/bin/
COPY --from=builder /bitcoin-cli /usr/bin
COPY bitcoin.conf /.bitcoin/bitcoin.conf

EXPOSE 9735

ENTRYPOINT ["gosu"]
# docker run -d --rm --name cln -p 9735:9735 -v /home/pi/lndata:/.lightning clnimg `id -u lnuser`:`id -g lnuser` lightningd
